const data = [
  {
    id: 1,
    parents: "Kyle Musk",
    gender: "F",
    birth: "21 Aug 2000",
    birthLocation: "Sao Tome and Principe",
    death: "23 February 1998",
    deathLocation: "Salt Lake City, Salt Lake Country",
    marriage: "",
    spouse: "Robert Musk",
    type: "P",
  },
  {
    id: 2,
    parents: "Robert Musk",
    gender: "M",
    birth: "13 july  1883",
    birthLocation: "Utah",
    death: "13 october 1956",
    deathLocation: "T ",
    marriage: "",
    spouse: "Kyle Musk",
    type: "P",
  },
  {
    id: 3,
    parents: "Elon Musk",
    gender: "M",
    birth: "1 jan 1858",
    birthLocation: "Salt Lake City, Salt Lake Country",
    death: "24 May 1924",
    deathLocation: "American folk , Utah ,Utah, USA",
    marriage: "1999",
    spouse: "Gillba Iza",
    type: "C",
  },
];
export default data;
